<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="yak" tagdir="/WEB-INF/tags/" %>

<yak:header title="User Agreement | Yakimbe" />

<div id="main-content">
    <div class="title">
        <h2>User Agreement</h2>
        <p>Modified:<br />February 15, 2010</p>
    </div>
    <div id="copy">
        <p>The following User Agreement ("Agreement") governs the use of www.yakimbe.com ("Web site"), including without limitation participation in its bulletin boards, forums, ads, chats, and all other areas (except to the extent stated otherwise on a specific page) as provided by Yakimbe Partners Media. ("Service Provider," "we," or "our").</p>
        <p>Please read the rules contained in this Agreement carefully. You can access this Agreement any time at <a href="<c:url value='/useragreement/' />">http://www.yakimbe.com/useragreement</a>. Your use of and/or registration on any aspect of the Web site will constitute your agreement to comply with these rules. If you cannot agree with these rules, please do not use the Web site.</p>
        <p>In addition to reviewing this Agreement, please read our <a href="<c:url value='/privacypolicy/' />">Privacy Policy</a>. Your use of the Web site constitutes agreement to its terms and conditions as well.</p>
        <p>The Agreement may be modified from time to time; the date of the most recent revisions will appear on this page, so check back often. Continued access of the Web site by you will constitute your acceptance of any changes or revisions to the Agreement.</p>
        <p>Your failure to follow these rules, whether listed below or in bulletins posted at various points in the Web site, may result in suspension or termination of your access to the Web site, without notice, in addition to Service Provider's other remedies.</p>

        <h3>Monitoring</h3>
        <p>We strive to provide an enjoyable online experience for our users, so we may monitor activity on the Web site, including without limitation the bulletin boards and forums to foster compliance with this Agreement. All users of the Web site hereby specifically agree to such monitoring. Nevertheless, we do not make any warranties or guarantees that: (1) the Web site, or any portion thereof, will be monitored for accuracy or unacceptable use, (2) apparent statements of fact will be authenticated, or (3) we will take any specific action (or any action at all) in the event of a dispute regarding compliance or non-compliance with this Agreement.</p>

        <h3>Medical Information Disclaimer</h3>
        <p>The Web site is not a forum for the exchange of medical information, advice or the promotion of self-destructive behavior (e.g., eating disorders, suicide). While you may freely discuss your troubles, you should not look to the Web site for information or advice on such topics. Instead, we recommend that you talk in person with a trusted adult that you know or a medical professional.<p>
        <p>THE INFORMATION ON THIS WEB SITE IS PROVIDED FOR EDUCATIONAL AND ENTERTAINMENT PURPOSES ONLY, AND IS IN NO WAY INTENDED TO DIAGNOSE, CURE, OR TREAT ANY MEDICAL OR OTHER CONDITION. ALWAYS SEEK THE ADVICE OF YOUR PHYSICIAN OR OTHER QUALIFIED HEALTH PROVIDER PRIOR TO STARTING ANY NEW DIET AND ASK YOUR DOCTOR ANY QUESTIONS YOU MAY HAVE REGARDING A MEDICAL CONDITION. IN ADDITION TO ALL OTHER LIMITATIONS AND DISCLAIMERS IN THIS AGREEMENT, SERVICE PROVIDER AND ITS THIRD PARTY PROVIDERS DISCLAIM ANY LIABILITY OR LOSS IN CONNECTION WITH THE CONTENT PROVIDED ON THIS WEB SITE.</p>

        <h3>Registration Information</h3>
        <p>Service Provider may at times require that you register and/or set up an account to use certain portions of the Web site, or the Web site as a whole. In order to do so, you may be provided, or required to choose, a password, user name, and/or other registration information (collectively, "Registration Information"). You agree and represent that all Registration Information provided by you is accurate and up-to-date. If any of your Registration Information changes, you must update it by using the appropriate update mechanism on the Web site, if available. Otherwise, contact our Privacy Policy Coordinator as described in our <a href="<c:url value='/guidelines/' />">Privacy Policy</a>.</p>

        <h3>Use of User ID/Password</h3>
        <p>If you register and/or set up an account on the Web site, you will be solely responsible for maintaining the confidentiality of your Registration Information. You may not authorize others to use your Registration Information. You may not sub-license, transfer, sell or assign your Registration Information and/or this Agreement to any third party without our written approval. Any attempt to do so will be null and void and shall be considered a material breach of this Agreement.</p>
        <p>You are solely responsible for all usage or activity on your account including, but not limited to, use of the account by any person who uses your Registration Information, with or without authorization, or who has access to any computer on which your account resides or is accessible.</p>
        <p>If you have reason to believe that your account is no longer secure (for example, in the event of a loss, theft or unauthorized disclosure or use of your Registration Information or any credit, debit or charge card number stored on the Web site), you must promptly change the affected Registration Information by using the appropriate update mechanism on the Web site, if available, or notify our Privacy Policy Coordinator as described in our <a href="<c:url value='/guidelines/' />">Privacy Policy</a>.</p>

        <h3>Fees And Payments</h3>
        <p>Service Provider or third parties may charge you fees for products or services offered for sale through the Web site, and/or for access to portions of the Web site or the Web site as a whole. You agree to pay all fees and charges, including applicable taxes, incurred through your account at the rates in effect for the billing period in which such fees and charges are incurred, including but not limited to charges for any products or services offered for sale through the Web site by Service Provider or by any third party vendor or provider (such fees, charges and taxes shall collectively be referred to as "Fees"). Service Provider reserves the right to change the amount of, or basis for determining, any Fees, and to institute new Fees, effective upon prior notice to you.</p>
        <p>If you submit your credit, debit or charge card information to Service Provider upon registration or otherwise, you give Service Provider permission to charge all Fees incurred through your account to the credit, debit or charge card you designate. Any additional Fees (other than renewal fees) will be charged at the time they are incurred. If payment cannot be charged to your credit, debit or charge card or your payment is returned to Service Provider for any reason, including charge back, Service Provider reserves the right to either suspend or terminate your account and all its obligations under this Agreement.</p>

        <h3>Use of the Service by You</h3>
        <p>The Web site is not intended for users under the age of 13, and Service Provider does not knowingly collect personally identifiable information from users under the age of 13. Such users are expressly prohibited from submitting their personally identifiable information to us, and from using portions of the Web site for which registration is required, such as our forums and chat areas; any information submitted by such users will not knowingly be used, posted, or retained by us.</p>
        <p>Unless otherwise specified, the Web site is intended for your personal use only. You may not authorize others to use the Web site, and you are responsible for all use of the Web site by you and by those you allow to use, or provide access to, the Web site. You may not impersonate, imitate or pretend to be somebody else when using the Web site.</p>
        <p>You may not provide to or post on or through the Web site any graphics, text, photographs, images, video, audio or other material that constitutes junk mail, spam, advertising, and/or commercial offers. You may not repeat the same posting multiple times in a day or week.</p>
        <p>You agree not to use any obscene, indecent, or offensive language or to provide to or post on or through the Web site any graphics, text, photographs, images, video, audio or other material that is defamatory, abusive, bullying, harassing, racist, hateful, or violent. You agree to refrain from ethnic slurs, religious intolerance, homophobia, and personal attacks when using the Web site.</p>
        <p>You further agree not to use any sexually suggestive language or to provide to or post on or through the Web site any graphics, text, photographs, images, video, audio or other material that is sexually suggestive or appeals to a prurient interest.</p>
        <p>You may not provide to or post on or through the Web site any graphics, text, photographs, images, video, audio or other material that invades anyone's privacy, or facilitates or encourages conduct that would constitute a criminal offense, give rise to civil liability, or that otherwise violates any local, state, federal, national or international law or regulation (e.g., drug use, underage drinking). You agree to use the Web site only for lawful purposes and you acknowledge that your failure to do so may subject you to civil and criminal liability. Do not provide to or post on or through the Web site any graphics, text, photographs, images, video, audio or other material that includes instructions for weapon and/or explosive manufacture or use.</p>
        <p>You are responsible for ensuring that any graphics, text, photographs, images, video, audio or other material you provide to or post on the Web site, including without limitation in bulletin boards, forums, personal ads, chats or elsewhere, does not violate the copyright, trademark, trade secret or any other personal or proprietary rights of any third party or is provided or posted with the permission of the owner(s) of such rights.</p>
        <p>The Web site contains graphics, text, photographs, images, video, audio, software, code, and other material that is provided by Service Provider or its licensors and is not clearly identified as, or intended, for your use, including without limitation the organization, design, compilation, and "look and feel" of the Web site, and advertising thereon ("Web site Content"). The Web site Content is protected by state, national and international copyright, trademark and other intellectual property laws, and is the property of Service Provider or its licensors. The copying, reproduction, publication, display, rearrangement, redistribution, modification, revision, alteration, cropping, re-sizing, reverse engineering, movement, removal, deletion, or other use or change by you, directly or indirectly, of any such Web site Content, including but not limited to the removal or alteration of advertising, is strictly prohibited.</p>
        <p>You may not in any way make commercial or other unauthorized use, by publication, re-transmission, distribution, performance, caching, or otherwise, of material obtained through the Web site, including without limitation the Assets or Web site Content, except as permitted by the Copyright Act or other law or as expressly permitted in writing by this Agreement, Service Provider or the Web site.</p>
        <p>You agree not to disrupt, overwhelm, attack, modify, reverse engineer or interfere with the Web site or its associated software, hardware and/or servers in any way, and you agree not to impede or interfere with others' use of the Web site.</p>
        <p>Other than connecting to Service Provider's servers by http requests using a Web browser, you may not attempt to gain access to Service Provider's servers by any means - including, without limitation, by using administrator passwords or by masquerading as an administrator while using the Web site or otherwise.</p>
        <p>You acknowledge that Service Provider has not reviewed and does not endorse the content of all sites linked to from this Web site and is not responsible for the content or actions of any other sites linked to from this Web site. Your linking to any service or site is at your sole risk.
        Comments by others are not endorsed by Service Provider</p>
        <p>Service Provider does not necessarily endorse, support, sanction, encourage, verify, or agree with the comments, opinions, or statements posted on forums, blogs or otherwise contained in the Web site. Any information or material placed online, including advice and opinions, are the views and responsibility of those who post the statements and do not necessarily represent the views of Service Provider or its third party service providers. You agree that Service Provider and its third party service providers are not responsible, and shall have no liability to you, with respect to any information or materials posted by others, including defamatory, offensive or illicit material, even material that violates this Agreement.</p>

        <h3>Use Of Material Supplied By You</h3>
        <p>For information regarding use of information about you that you may supply or communicate to the Web site, please see our <a href="<c:url value='/guidelines/' />">Privacy Policy</a>. Except as expressly provided otherwise in the <a href="<c:url value='/guidelines/' />">Privacy Policy</a>, you agree that by posting messages, uploading files, inputting data, or engaging in any other form of communication with or through the Web site, you grant us a royalty-free, perpetual, non-exclusive, unrestricted, worldwide license to use, reproduce, modify, adapt, translate, enhance, transmit, distribute, publicly perform, display, or sublicense any such communication in any medium (now in existence or hereinafter developed) and for any purpose, including commercial purposes, and to authorize others to do so. In addition, please be aware that information you disclose in publicly accessible portions of the Web site will be available to all users of the Web site, so you should be mindful of personal information and other content you may wish to post.</p>

        <h3>Copyright Complaints</h3>
        <p>Service Provider respects the intellectual property of others, and we ask our users to do the same. Service Provider may, in appropriate circumstances and at its discretion, suspend or terminate the access of and take other action against users, subscribers, registrants and account holders who infringe the copyright rights of others.</p>
        <p>If you believe that your work has been copied and is accessible on the Web site in a way that constitutes copyright infringement, or that the Web site contains links or other references to another online location that contains material or activity that infringes your copyright rights, you may notify Service Provider by providing the following information (as required by the Online Copyright Infringement Liability Limitation Act of the Digital Millennium Copyright Act, 17 U.S.C. sec. 512) to our copyright agent set forth below:</p>
        <p>A physical or electronic signature of person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</p>
        <p>Identification of the copyrighted work claimed to have been infringed, or if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site;</p>
        <p>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit Service Provider to locate the material;</p>
        <p>Information reasonably sufficient to permit Service Provider to contact the complaining party, such as an address, telephone number, and if available, an electronic mail address at which the complaining party may be contacted;</p>
        <p>A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</p>
        <p>A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed</p>

        <p><strong>Copyright Agent:</strong>
        Jesse Woodruff<br />
        jesse@yakimbe.com<br /></p>
        <p><strong>Note:</strong> Only copyright complaints should be sent to agent. No other communications will be accepted or responded to. For communications on other matters, please contact Service Provider as described on the Web site, or e-mail webguy@yakimbe.com.

        <h3>Merchandise Sold On or Through the Web Site</h3>
        <p>Neither Service Provider nor its third party service providers make any warranties with respect to any of the merchandise, products, and/or services featured, mentioned, or sold by others on or through the Web site. Transactions for any such item shall be between the user and the third party seller, without any involvement of Service Provider or its third party service providers. You agree that Service Provider and its third party service providers are not responsible, and shall have no liability to you, with respect to merchandise, products, and/or services featured, mentioned, or sold by others on or through the Web site, including illegal, offensive or illicit items, even items that violates this Agreement.</p>

        <h3>Indemnification</h3>
        <p>You agree to indemnify Service Provider and its affiliates, employees, agents, representatives and third party service providers, and to defend and hold each of them harmless, from any and all claims and liabilities (including attorneys fees) which may arise from your submissions, from your unauthorized use of material obtained through the Web site, or from your breach of this Agreement, or from any such acts through your use of the Web site.</p>

        <h3>Editing And Deletions</h3>
        <p>Service Provider reserves the right, but undertakes no duty, to review, edit, move or delete any material provided for display or placed on the Web site or its bulletin boards, in its sole discretion, without notice.</p>

        <h3>Additional Rules</h3>
        <p>Service Provider reserves the right to post, from time to time, additional rules of usage that apply to specific parts of the Web site. Such additional rules will be posted in the relevant parts of the Web site. Your continued use of the Web site constitutes your agreement to comply with these additional rules.</p>

        <h3>Disclaimer Of Warranty And Limitation Of Liability</h3>
        <p>YOU ACKNOWLEDGE THAT YOU ARE USING THE WEB SITE AT YOUR OWN RISK. THE WEB SITE IS PROVIDED "AS IS", AND THE SERVICE PROVIDER, ITS AFFILIATES AND ITS THIRD PARTY SERVICE PROVIDERS HEREBY EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES, EXPRESS AND IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF ACCURACY, RELIABILITY, TITLE, MERCHANTABILITY, NON-INFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE OR ANY OTHER WARRANTY, CONDITION, GUARANTEE OR REPRESENTATION, WHETHER ORAL, IN WRITING OR IN ELECTRONIC FORM, INCLUDING BUT NOT LIMITED TO THE ACCURACY OR COMPLETENESS OF ANY INFORMATION CONTAINED THEREIN OR PROVIDED BY THE WEB SITE. SERVICE PROVIDER, ITS AFFILIATES, AND ITS THIRD PARTY SERVICE PROVIDERS DO NOT REPRESENT OR WARRANT THAT ACCESS TO THE WEB SITE WILL BE UNINTERRUPTED OR THAT THERE WILL BE NO FAILURES, ERRORS OR OMISSIONS OR LOSS OF TRANSMITTED INFORMATION, OR THAT NO VIRUSES WILL BE TRANSMITTED ON THE WEB SITE.</P>
        <p>SERVICE PROVIDER, ITS AFFILIATES AND ITS THIRD PARTY SERVICE PROVIDERS SHALL NOT BE LIABLE TO YOU OR ANY THIRD PARTIES FOR ANY DIRECT, INDIRECT, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES ALLEGEDLY SUSTAINED ARISING OUT OF THIS AGREEMENT, THE PROVIDING OF THE WEB SITE HEREUNDER, THE SALE OR PURCHASE OF ANY GOODS OR MERCHANDISE, YOUR ACCESS TO OR INABILITY TO ACCESS THE WEB SITE, INCLUDING FOR VIRUSES ALLEGED TO HAVE BEEN OBTAINED FROM THE WEB SITE, YOUR USE OF OR RELIANCE ON THE WEB SITE OR ANY OF THE MERCHANDISE, INFORMATION OR MATERIALS AVAILABLE ON THE WEB SITE, REGARDLESS OF THE TYPE OF CLAIM OR THE NATURE OF THE CAUSE OF ACTION, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME STATES DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU. YOU MAY ALSO HAVE OTHER RIGHTS THAT VARY FROM STATE TO STATE.
        <p>YOU HEREBY AGREE TO RELEASE SERVICE PROVIDER, ITS AFFILIATES AND THIRD-PARTY SERVICE PROVIDERS, AND EACH OF THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, AND AGENTS FROM CLAIMS, DEMANDS AND DAMAGES (ACTUAL AND CONSEQUENTIAL) OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, SUSPECTED AND UNSUSPECTED, DISCLOSED AND UNDISCLOSED ("CLAIMS"), ARISING OUT OF OR IN ANY WAY CONNECTED WITH YOUR USE OF THIS SITE. IF YOU ARE A CALIFORNIA RESIDENT, YOU WAIVE CALIFORNIA CIVIL CODE SECTION 1542, WHICH STATES, IN PART: "A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR".</p>

        <h3>Termination Or Suspension Of Access To The Web site</h3>
        <p>Service Provider has the right to terminate and/or suspend your ability to access the Web site or any portion thereof, for any or no reason, without notice.</p>

        <h3>Jurisdiction</h3>
        <p>Service Provider makes no representation that materials on the Web site are appropriate, available or legal in any particular location. Those who choose to access the Web site do so on their own initiative and are responsible for compliance with local laws, if and to the extent local laws are applicable.</p>
        <p>You agree that this Agreement, for all purposes, shall be governed and construed in accordance with the laws of the State of Michigan applicable to contracts to be wholly performed therein, and any action based on, relating to, or alleging a breach of this Agreement must be brought in a state or federal court in Michigan. In addition, both parties agree to submit to the exclusive personal jurisdiction and venue of such courts.</p>
        <p>The following provision applies to all visitors to the Web site (which shall include persons and representatives of legal entities, whether such representatives are persons or digital engines of any kind that crawl, index, scrape, copy, store or transmit digital content). By accessing this Web site, you specifically acknowledge and agree that: (i) Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistributed directly or indirectly in any medium; (ii) no Associated Press materials nor any portion thereof may be stored in a computer except for personal and non-commercial use; (iii) the Associated Press will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing; (iv) the Associated Press is an intended third party beneficiary of these terms and conditions and it may exercise all rights and remedies available to it; and (v) the Associated Press reserves the right to audit possible unauthorized commercial use of Associated Press materials or any portion thereof at any time.</p>
        <p>If you don't agree to the terms contained in this Agreement, please exit the Web site by clicking the Back button on your browser to return to the previous page.</p>
     </div>
</div>

<%@include file="/WEB-INF/jspf/footer.jspf" %>
